development:
  adapter: sqlite3
  encoding: utf8
  database: project_development
  host: localhost
  pool: 5
  password:

test: &test
  adapter: sqlite3
  encoding: utf8
  database: project_test
  host: localhost
  pool: 5
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: project_production
  host: localhost
  pool: 5
  password:

cucumber:
  <<: *test
