# frozen_string_literal: true

source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.2'
gem 'bootsnap', require: false
gem 'ffi'
gem 'listen'
gem 'nokogiri'
gem 'rails', '~> 5'

gem 'mini_racer'

gem 'passwordless', git: 'https://github.com/mikker/passwordless.git', branch: 'master'

gem 'autoprefixer-rails'

gem 'bootstrap-sass'
gem 'bootswatch-rails'
gem 'sassc-rails'

gem 'bootstrap_form'

gem 'font-awesome-rails'

gem 'simple_form'

gem 'will_paginate'

gem 'will_paginate-bootstrap'

gem 'kaminari'

gem 'redis'

gem 'execjs'

# Use SCSS for stylesheets
gem 'sass-rails'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

gem "letter_opener", :group => :development


group :test, :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'capybara'
  gem 'capybara-email'
  gem 'did_you_mean'
  gem 'cucumber-rails', require: false
  # database_cleaner is not mandatory, but highly recommended
  gem 'database_cleaner'
  gem 'email_spec'
  gem 'meta_request'
  gem 'rails-controller-testing'
  gem 'record_tag_helper'
  gem 'rspec-rails'
  gem 'rubocop', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec', require: false
  gem 'sqlite3'
end

group :production do
  # Use PostgreSql as the database for Active Record
  gem 'pg'
end

ruby '2.7.2'
