source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 4.2'

gem 'nokogiri', '1.9.1'

gem 'ffi', '1.12.2'

gem 'sprockets-rails', :require => 'sprockets/railtie'

gem 'bootstrap-sass', '~> 3.4.1'
gem 'sassc-rails', '>= 2.1.0'

gem 'bootswatch-rails'

gem 'autoprefixer-rails'

gem 'bootstrap_form'

gem "font-awesome-rails", '4.7.0.5'

gem "simple_form"

gem 'will_paginate'

gem 'will_paginate-bootstrap'

gem 'kaminari'

gem 'redis', '4.1.1'

gem 'mini_racer'

gem 'execjs'


gem 'devise'

gem 'omniauth'

# Use SCSS for stylesheets
gem 'sass-rails'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

group :test, :nokogiri do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'meta_request'
  gem 'sqlite3', '~> 1.3.10'
  gem 'rspec-rails', '~> 3.9'
  gem 'capybara', '~> 2.4'
end

group :produaction do
  # Heroku
  gem 'rails_12factor', group: :production
  # Use PostgreSql as the database for Active Record
  gem "pg"
  # Use unicorn as the app server
  gem 'unicorn'

end

ruby "~> 2.3"
